# Generated by Django 5.0.7 on 2024-08-01 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_nat_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11, 'Phone number must be at exactly 11 digits in Iran to receive sms'), django.core.validators.MaxLengthValidator(11, 'Phone number must be at exactly 11 digits in Iran to receive sms')], verbose_name='Phone number'),
        ),
    ]
