# Generated by Django 5.1.2 on 2025-11-20 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profilepicture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        11,
                        "Phone number must be exactly 11 digits in Iran to receive sms",
                    ),
                    django.core.validators.MaxLengthValidator(
                        11,
                        "Phone number must be exactly 11 digits in Iran to receive sms",
                    ),
                ],
                verbose_name="Phone number",
            ),
        ),
    ]
