# Generated by Django 5.1.14 on 2026-01-01 07:08

import confectionery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_phonenumber_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilepicture",
            name="image",
            field=models.ImageField(
                upload_to=confectionery.models.upload_to_path, verbose_name="Image"
            ),
        ),
    ]
