# Generated by Django 5.1.14 on 2026-01-07 07:28

import confectionery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_profilepicture_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilepicture",
            name="image",
            field=models.ImageField(
                upload_to=confectionery.models.upload_to_path,
                validators=[confectionery.models.validate_image],
                verbose_name="Image",
            ),
        ),
    ]
