# Generated by Django 5.0.7 on 2024-07-25 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('product_type', models.CharField(choices=[('cake', 'Cake'), ('pastry', 'Pastry'), ('bread', 'Bread')], max_length=8, verbose_name='Product Type')),
                ('flour_type', models.CharField(choices=[('wheat', 'Wheat'), ('corn', 'Corn'), ('rice', 'Rice')], max_length=8, verbose_name='Flour Type')),
                ('sugar_rate', models.CharField(choices=[('high', 'High'), ('avg', 'Average'), ('low', 'Low')], max_length=8, verbose_name='Sugar Rate')),
                ('fat_rate', models.CharField(choices=[('high', 'High'), ('avg', 'Average'), ('low', 'Low')], max_length=8, verbose_name='Fat Rate')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Weight')),
                ('price_toman', models.PositiveIntegerField(verbose_name='Price Toman')),
                ('preparation_time', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Preparation Time')),
                ('ingredients', models.CharField(max_length=1024, verbose_name='Ingredients')),
                ('expiration_days', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(60)], verbose_name='Expiration Days')),
                ('main_image', models.ImageField(blank=True, upload_to='main_images/', verbose_name='Main Image')),
                ('extra_information', models.TextField(blank=True, max_length=10000, verbose_name='Extra Information')),
            ],
        ),
    ]
