# Generated by Django 5.0.7 on 2024-07-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confectionery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flour_type',
            field=models.CharField(choices=[('wheat', 'Wheat'), ('corn', 'Corn'), ('rice', 'Rice'), ('oat', 'Oat')], max_length=8, verbose_name='Flour Type'),
        ),
    ]
