# Generated by Django 5.0.7 on 2024-08-01 16:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confectionery', '0005_alter_productananymoususercomment_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productananymoususercomment',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcustomusercomment',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcustomusercomment',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
