# Generated by Django 5.0.7 on 2024-08-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confectionery', '0006_productananymoususercomment_datetime_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionsCritics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('text', models.TextField(max_length=10000, verbose_name='Text')),
                ('seen', models.BooleanField(default=False, verbose_name='Seen')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Time Created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Last Time Edited')),
            ],
        ),
        migrations.AlterField(
            model_name='productananymoususercomment',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Time Created'),
        ),
        migrations.AlterField(
            model_name='productcustomusercomment',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Time Created'),
        ),
        migrations.AlterField(
            model_name='productcustomusercomment',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Time Edited'),
        ),
    ]
