# Generated by Django 5.0.7 on 2024-08-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confectionery', '0008_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('talent', models.CharField(max_length=255, verbose_name='Talent')),
                ('image', models.ImageField(blank=True, upload_to='chef_images/', verbose_name='Image')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='description')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('facebook', models.CharField(blank=True, max_length=255, verbose_name='facebook')),
                ('instagram', models.CharField(blank=True, max_length=255, verbose_name='instagram')),
                ('linkedin', models.CharField(blank=True, max_length=255, verbose_name='linkedin')),
                ('twitter', models.CharField(blank=True, max_length=255, verbose_name='twitter')),
            ],
        ),
    ]
