# Generated by Django 5.0.7 on 2024-08-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confectionery', '0009_chef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, verbose_name='Twitter'),
        ),
    ]
