# Generated by Django 5.0.7 on 2024-08-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confectionery', '0010_alter_chef_facebook_alter_chef_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug'),
        ),
    ]
