# Generated by Django 5.0.7 on 2024-08-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confectionery', '0011_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, db_collation='utf8_persian_ci', unique=True, verbose_name='Slug'),
        ),
    ]
