# Generated by Django 5.1.14 on 2025-12-31 07:25

import confectionery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confectionery', '0012_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, upload_to=confectionery.models.upload_to_path, verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug'),
        ),
    ]
