# Generated by Django 5.1.14 on 2025-12-31 14:08

import confectionery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confectionery', '0013_alter_product_main_image_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='image',
            field=models.ImageField(blank=True, upload_to=confectionery.models.upload_to_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=confectionery.models.upload_to_path, verbose_name='image'),
        ),
    ]
