# Generated by Django 5.1.14 on 2026-01-07 07:28

import confectionery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("confectionery", "0014_alter_chef_image_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chef",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=confectionery.models.upload_to_path,
                validators=[confectionery.models.validate_image],
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ImageField(
                blank=True,
                upload_to=confectionery.models.upload_to_path,
                validators=[confectionery.models.validate_image],
                verbose_name="Main Image",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to=confectionery.models.upload_to_path,
                validators=[confectionery.models.validate_image],
                verbose_name="image",
            ),
        ),
    ]
