# Generated by Django 5.0.7 on 2024-08-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='madval_tracking_code',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
