# Generated by Django 5.0.7 on 2024-08-22 08:28

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_madval_tracking_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=orders.models.generate_random_code, max_length=31, unique=True, verbose_name='متن')),
                ('discount_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مقدار تخفیف')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='درصد تخفیف')),
                ('max_discount_amount', models.PositiveIntegerField(default=150000, verbose_name='حداکثر مقدار تخفیف')),
                ('limit', models.PositiveIntegerField(default=10)),
                ('used_times', models.PositiveIntegerField(default=0)),
                ('expiration_date', models.DateField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.discount', verbose_name='Discount'),
        ),
    ]
