# Generated by Django 5.0.7 on 2024-08-23 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_discount_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='same_user_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='Same User Limit'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='expiration_date',
            field=models.DateField(verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='limit',
            field=models.PositiveIntegerField(default=10, verbose_name='Limit'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='used_times',
            field=models.PositiveIntegerField(default=0, verbose_name='Used Times'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.discount', verbose_name='تخفیف'),
        ),
    ]
