# Generated by Django 5.0.7 on 2024-08-23 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_discount_same_user_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='user',
        ),
        migrations.AddField(
            model_name='discount',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='discounts', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='expiration_date',
            field=models.DateField(verbose_name='تاریخ مصرف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='limit',
            field=models.PositiveIntegerField(default=10, verbose_name='حداکثر تعداد استفاده'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='same_user_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='حداکثر تعداد استفاده برای یک کاربر'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='used_times',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد دفعات استفاده شده'),
        ),
    ]
