# Generated by Django 5.1.2 on 2025-11-20 15:01

import django.core.validators
import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("confectionery", "0012_alter_product_slug"),
        ("orders", "0005_remove_discount_user_discount_users_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="discount_amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Discount Amount"
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=2,
                null=True,
                verbose_name="Discount Percentage",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="expiration_date",
            field=models.DateField(verbose_name="Expiration Date"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="limit",
            field=models.PositiveIntegerField(default=10, verbose_name="Limit"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="max_discount_amount",
            field=models.PositiveIntegerField(
                default=150000, verbose_name="Max Discount Amount"
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="same_user_limit",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Same User Limit"
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="text",
            field=models.CharField(
                default=orders.models.generate_random_code,
                max_length=31,
                unique=True,
                verbose_name="Text",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="used_times",
            field=models.PositiveIntegerField(default=0, verbose_name="Used Times"),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.TextField(max_length=500, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="order",
            name="datetime_created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date Time of creation"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="datetime_modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date Time of last edit"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="orders.discount",
                verbose_name="Discount",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=255, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Is Paid?"),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=255, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_notes",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="Order Notes"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(
                max_length=14,
                validators=[
                    django.core.validators.MinLengthValidator(
                        11, "Phone number should be at least 11 digits"
                    ),
                    django.core.validators.MaxLengthValidator(
                        14, "Phone number should be at most 14 digits"
                    ),
                ],
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.PositiveIntegerField(verbose_name="Price"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="confectionery.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Quantity"),
        ),
    ]
